version: '3.7'

services:
  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--global.sendanonymoususage=false"
    ports:
      - "80:80" ## web
      - "8080:8080" ## traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
